services:
  negpy:
    build:
      context: .
      network: host
    container_name: negpy
    volumes:
      - ./:/app
      - ${NEGPY_HOST_DIR}:/app/user
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - NEGPY_USER_DIR=user
      - DISPLAY=${DISPLAY}
    network_mode: host