services:
  negative-py:
    build:
      context: .
      network: host
    container_name: negative-py
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - ${NEGATIVEPY_HOST_DIR}:/app/user
    environment:
      - NEGATIVEPY_USER_DIR=user
    restart: unless-stopped
