[theme]
base = "dark"

# General color setup - Monochrome with Red Accent
textColor = "#c3c3c3"
primaryColor = "#b10000" # sliders, button accents, etc
secondaryBackgroundColor = "#080808" # Left panel BG

# Main section BG
backgroundColor = "#161616"

# Widgets
showWidgetBorder = true
borderColor = "#181818"          # Subtle border contrast

# Base text
font = "'Roboto':https://fonts.googleapis.com/css2?family=Roboto:wght@300..700&display=swap"
baseFontWeight = 400
baseFontSize = 18

# Heading text
headingFont = "Roboto"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "2.0rem", "1.5rem"]

[client]
toolbarMode = "minimal"
